# Generated by Django 3.0.3 on 2020-03-02 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.AutoField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(max_length=200)),
                ('errata_doc', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Game_news',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.TextField(null=True)),
                ('news_text', models.TextField()),
                ('news_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=200)),
                ('game_type', models.CharField(max_length=200)),
                ('game_introduction', models.CharField(max_length=200)),
                ('game_rules', models.CharField(max_length=200)),
                ('game_purchase', models.CharField(max_length=200)),
                ('game_score', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('user_password', models.CharField(max_length=200)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=200, unique=True)),
                ('user_tags', models.CharField(max_length=200, null=True)),
                ('user_community', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_publisher', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_likecount', models.IntegerField()),
                ('post_communityid', models.IntegerField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_title', models.ForeignKey(default=models.AutoField(primary_key=True, serialize=False), on_delete=django.db.models.deletion.CASCADE, to='GCapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GCapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('FAQ_id', models.AutoField(primary_key=True, serialize=False)),
                ('FAQ_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GCapp.Games')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_publisher', models.CharField(max_length=200)),
                ('comment_likecount', models.IntegerField()),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('comment_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GCapp.Games')),
            ],
        ),
    ]
