# Generated by Django 3.0.3 on 2020-03-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0002_auto_20200302_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
