# Generated by Django 3.0.3 on 2020-03-03 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0003_auto_20200303_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='user_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=32),
        ),
    ]
