# Generated by Django 3.0.3 on 2020-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0004_auto_20200303_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-register_time'], 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterField(
            model_name='users',
            name='user_community',
            field=models.CharField(choices=[('N/A', 'N/A'), ('gamechat', 'GameChat'), ('gamequestions', 'GameQuestions'), ('bugs', 'Bugs'), ('find users', 'FindUsers'), ('avatars', 'Avatars'), ('stats', 'Stats')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_tags',
            field=models.CharField(choices=[('N/A', 'N/A'), ('adventure', 'Adventure'), ('ancient', 'Ancient'), ('educational', 'Educational'), ('fighting', 'Fighting'), ('racing', 'Racing'), ('sports', 'Sports'), ('wargame', 'Wargame'), ('zombies', 'Zombies')], default='N/A', max_length=200),
        ),
    ]
