# Generated by Django 3.0.3 on 2020-03-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0005_auto_20200303_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecollection',
            name='collection_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GCapp.Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamecollection',
            name='collection_game',
            field=models.CharField(max_length=200),
        ),
    ]
