# Generated by Django 3.0.3 on 2020-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0007_auto_20200304_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecollection',
            name='collection_game',
            field=models.CharField(max_length=200),
        ),
    ]
