# Generated by Django 3.0.3 on 2020-03-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0008_auto_20200304_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecollection',
            name='collection_gameid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GCapp.Games'),
            preserve_default=False,
        ),
    ]
