# Generated by Django 3.0.3 on 2020-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0009_gamecollection_collection_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('adventure', 'Adventure'), ('ancient', 'Ancient'), ('educational', 'Educational'), ('fighting', 'Fighting'), ('racing', 'Racing'), ('sports', 'Sports'), ('wargame', 'Wargame'), ('zombies', 'Zombies')], default='N/A', max_length=200),
        ),
    ]
