# Generated by Django 3.0.3 on 2020-03-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0012_auto_20200306_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecollection',
            name='collection_gameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GCapp.Games'),
        ),
    ]
