# Generated by Django 3.0.3 on 2020-03-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0013_auto_20200306_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GCapp.Games'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(),
        ),
    ]
