# Generated by Django 3.0.3 on 2020-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0014_auto_20200309_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_likecount',
            field=models.IntegerField(default=0),
        ),
    ]
