# Generated by Django 3.0.3 on 2020-03-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0016_auto_20200309_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(choices=[('N/A', 'N/A'), ('gamechat', 'GameChat'), ('gamequestions', 'GameQuestions'), ('bugs', 'Bugs'), ('find users', 'FindUsers'), ('avatars', 'Avatars'), ('stats', 'Stats')], default='N/A', max_length=200),
        ),
    ]
