# Generated by Django 3.0.3 on 2020-03-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0017_auto_20200309_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='errata_doc',
        ),
        migrations.AddField(
            model_name='faq',
            name='FAQ_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GCapp.Games'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='errata_doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='faq',
            name='FAQ_text',
            field=models.TextField(),
        ),
    ]
