# Generated by Django 3.0.3 on 2020-03-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0018_auto_20200309_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_communityid',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GCapp.Community'),
            preserve_default=False,
        ),
    ]
