# Generated by Django 3.0.3 on 2020-03-09 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GCapp', '0019_auto_20200309_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GCapp.Users'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_title',
            field=models.CharField(max_length=300),
        ),
    ]
